name: prana_task3
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "1.0.0"

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/atom.png"
  image_path_ios: "images/atom.png"
  image_path_android: "images/atom.png"
  adaptive_icon_background: "images/atom.png"
  adaptive_icon_foreground: "images/atom.png"

flutter:
  uses-material-design: true
